### ISSUE TITLE
Design a kick-ass home-page

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#21]
We are rebranding... lets show it! 

Lets give some love to our home-page, and make it pop so people want to stay on the site.

**Comment by SirLich** [comment]
# Theme Config: Homepage

VitePress provides a homepage layout. To use it, specify `home: true` plus some other metadata in your root `index.md`'s [YAML frontmatter](../guide/frontmatter). This is an example of how it works:

```yaml
---
home: true
heroImage: /logo.png
heroAlt: Logo image
heroText: Hero Title
tagline: Hero subtitle
actionText: Get Started
actionLink: /guide/
features:
  - title: Simplicity First
    details: Minimal setup with markdown-centered project structure helps you focus on writing.
  - title: Vue-Powered
    details: Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue.
  - title: Performant
    details: VitePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded.
footer: MIT Licensed | Copyright © 2019-present Evan You
---

```
